language: go
go:
  - tip
before_install:
  - go get github.com/takonews/takonews-api
  - go get github.com/tools/godep
install:
  - godep restore
before_script:
  - chmod +x codecov.sh
  - cp config/database.yml.sample config/database.yml
  - mysql -e 'create database takonews_development;'
script:
  - ./codecov.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
